title: EESRF HPC User Guide
description: User guide of HPC at EESRF
theme: just-the-docs

url: https://qingli411.github.io/eesrf-hpc-user-guide

aux_links:
  Template Repository: https://github.com/qingli411/eesrf-hpc-user-guide
