title: EESRF HPC User Guide
description: User guide of HPC at EESRF
theme: just-the-docs

url: https://qingli411.github.io/eesrf-hpc-user-guide

aux_links:
  View page source: https://github.com/qingli411/eesrf-hpc-user-guide

callouts:
  note:
    title: Note
    color: purple
    opacity: 0.3

